DROP TABLE IF EXISTS subscribers;

CREATE TABLE subscribers (
    id SERIAL PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    subscribed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS vita;

CREATE TABLE vita (
    id SERIAL PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    post_id INTERGER NOT NULL UNIQUE,
    post_date DATETIME NOT NULL,
    post_url VARCHAR(512) NOT NULL UNIQUE
);

DROP TABLE IF EXISTS peopo;

CREATE TABLE peopo (
    id SERIAL PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    post_id INTERGER NOT NULL UNIQUE,
    post_date DATETIME NOT NULL,
    post_url VARCHAR(512) NOT NULL UNIQUE
)

